export interface Planta {
  id: number
  nombre_comun: string
  nombre_cientifico: string
  familia: string
  descripcion: string
  usos: string
  conservacion?: string
  imagen: string
  categoria: string
  dificultad_cultivo: "Fácil" | "Moderada" | "Difícil"
  riego: "Bajo" | "Moderado" | "Alto"
  sol: "Pleno sol" | "Sol parcial" | "Sombra"
  datos_curiosos: string
  emoji: string
  color: string
}

export const plantasBCS: Planta[] = [
  {
    id: 1,
    nombre_comun: "Biznaga",
    nombre_cientifico: "Ferocactus townsendianus",
    familia: "Cactaceae",
    descripcion:
      "Cactus globoso-cilíndrico de 30 – 70 cm, 13 – 21 costillas, espinas robustas rojizas/amarillas; flores amarillas-rojizas en el ápice; fruto esférico amarillo y comestible, sabor ácido.",
    usos: "Ornamental; alimento para el ganado.",
    conservacion: "NOM-059 Amenazada; CITES Apéndice II",
    imagen: "/placeholder.svg?height=300&width=400",
    categoria: "Cactáceas",
    dificultad_cultivo: "Moderada",
    riego: "Bajo",
    sol: "Pleno sol",
    datos_curiosos:
      "Sus frutos tienen un sabor ácido característico y son una importante fuente de alimento para la fauna del desierto.",
    emoji: "🌵",
    color: "bg-green-500",
  },
  {
    id: 2,
    nombre_comun: "Cacachila",
    nombre_cientifico: "Karwinskia humboldtiana",
    familia: "Rhamnaceae",
    descripcion:
      "Arbusto-árbol 2 – 5 m, ramas espinosas, hojas brillantes; flores verdosas en racimos; bayas negras muy tóxicas.",
    usos: "Medicinal (controlado); tóxica.",
    conservacion: "Preocupación menor",
    imagen: "/placeholder.svg?height=300&width=400",
    categoria: "Medicinales",
    dificultad_cultivo: "Difícil",
    riego: "Bajo",
    sol: "Pleno sol",
    datos_curiosos:
      "También conocida como Tullidora, sus bayas negras son extremadamente tóxicas y pueden causar parálisis.",
    emoji: "⚠️",
    color: "bg-red-500",
  },
  {
    id: 3,
    nombre_comun: "Cafecillo",
    nombre_cientifico: "Senna villosa",
    familia: "Fabaceae",
    descripcion:
      "Arbusto 1.5 – 4 m, hojas compuestas pinnadas; flores amarillas en racimos; vainas planas con varias semillas; común en suelos secos.",
    usos: "Medicinal; combustible; maderable.",
    imagen: "/placeholder.svg?height=300&width=400",
    categoria: "Leguminosas",
    dificultad_cultivo: "Fácil",
    riego: "Bajo",
    sol: "Pleno sol",
    datos_curiosos: "Sus flores amarillas brillantes aparecen principalmente durante la temporada de lluvias.",
    emoji: "🌼",
    color: "bg-yellow-500",
  },
  {
    id: 4,
    nombre_comun: "Candelilla",
    nombre_cientifico: "Euphorbia lomelii",
    familia: "Euphorbiaceae",
    descripcion:
      "Suculenta de tallos cilíndricos erectos (hasta 1.5 m) sin hojas; flores rojizas en 'zapatito' en otoño-primavera.",
    usos: "Ornamental; medicinal.",
    conservacion: "CITES Apéndice II",
    imagen: "/placeholder.svg?height=300&width=400",
    categoria: "Suculentas",
    dificultad_cultivo: "Moderada",
    riego: "Bajo",
    sol: "Pleno sol",
    datos_curiosos: "Sus tallos cilíndricos sin hojas le dan una apariencia única, parecida a velas verdes.",
    emoji: "🕯️",
    color: "bg-green-400",
  },
  {
    id: 5,
    nombre_comun: "Cardón Barbón",
    nombre_cientifico: "Pachycereus pecten-aboriginum",
    familia: "Cactaceae",
    descripcion:
      "Cactus columnar gigante (hasta 15 m), muchos brazos; flores nocturnas blancas-crema; fruto espinoso con pulpa comestible.",
    usos: "Medicinal; ornamental; alimenticio; artesanal.",
    conservacion: "Preocupación menor; CITES Apéndice II",
    imagen: "/placeholder.svg?height=300&width=400",
    categoria: "Cactáceas",
    dificultad_cultivo: "Moderada",
    riego: "Bajo",
    sol: "Pleno sol",
    datos_curiosos:
      "Puede vivir más de 200 años y sus flores solo se abren durante la noche para ser polinizadas por murciélagos.",
    emoji: "🌵",
    color: "bg-green-600",
  },
  {
    id: 6,
    nombre_comun: "Celosa",
    nombre_cientifico: "Mimosa tricephala var. lagunensis",
    familia: "Fabaceae",
    descripcion:
      "Arbusto espinoso 1 – 2 m, hojas bipinnadas; flores globosas rosa-púrpura; muy tolerante a sequía extrema.",
    usos: "Forraje; medicinal; ornamental; combustible.",
    imagen: "/placeholder.svg?height=300&width=400",
    categoria: "Leguminosas",
    dificultad_cultivo: "Fácil",
    riego: "Bajo",
    sol: "Pleno sol",
    datos_curiosos: "También conocida como Uña de Gato por sus espinas curvadas que se adhieren fácilmente.",
    emoji: "🌸",
    color: "bg-pink-500",
  },
  {
    id: 7,
    nombre_comun: "Chicura",
    nombre_cientifico: "Ambrosia ambrosioides",
    familia: "Asteraceae",
    descripcion:
      "Hierba/subarbusto 1 – 2 m, hojas lobuladas grisáceas con olor fuerte; flores amarillo-verdoso en extremos.",
    usos: "Medicinal; fijadora de suelos.",
    imagen: "/placeholder.svg?height=300&width=400",
    categoria: "Medicinales",
    dificultad_cultivo: "Fácil",
    riego: "Bajo",
    sol: "Pleno sol",
    datos_curiosos: "Su olor fuerte y característico la hace fácilmente reconocible en el campo.",
    emoji: "🌿",
    color: "bg-gray-500",
  },
  {
    id: 8,
    nombre_comun: "Chilicote",
    nombre_cientifico: "Erythrina flabelliformis",
    familia: "Fabaceae",
    descripcion:
      "Árbol-arbusto 3 – 10 m, ramas espinosas; flores rojas-naranjas vistosas; vainas con semillas rojas tóxicas.",
    usos: "Combustible; maderable; ornamental; (semillas tóxicas).",
    conservacion: "Preocupación menor",
    imagen: "/placeholder.svg?height=300&width=400",
    categoria: "Ornamentales",
    dificultad_cultivo: "Moderada",
    riego: "Moderado",
    sol: "Pleno sol",
    datos_curiosos:
      "También conocido como Colorín o Corcho, sus flores rojas son muy llamativas pero sus semillas son tóxicas.",
    emoji: "🌺",
    color: "bg-red-400",
  },
  {
    id: 9,
    nombre_comun: "Chiltepín",
    nombre_cientifico: "Capsicum annuum var. glabriusculum",
    familia: "Solanaceae",
    descripcion: "Hierba-arbusto 0.5 – 1.5 m; frutos pequeños rojos muy picantes; planta resistente a sequía.",
    usos: "Medicinal; alimento culinario.",
    imagen: "/placeholder.svg?height=300&width=400",
    categoria: "Comestibles",
    dificultad_cultivo: "Moderada",
    riego: "Moderado",
    sol: "Sol parcial",
    datos_curiosos: "Es considerado el chile más picante de México y crece de forma silvestre en el desierto.",
    emoji: "🌶️",
    color: "bg-red-600",
  },
  {
    id: 10,
    nombre_comun: "Cholla Pelona",
    nombre_cientifico: "Cylindropuntia cholla",
    familia: "Cactaceae",
    descripcion:
      "Cactus articulado hasta 2 m, espinas amarillas/blancas; flores grandes amarillas-rojas; fruto espinoso carnoso.",
    usos: "Forraje; combustible; medicinal; ornamental; alimenticio; artesanal.",
    conservacion: "Preocupación menor; CITES Apéndice II",
    imagen: "/placeholder.svg?height=300&width=400",
    categoria: "Cactáceas",
    dificultad_cultivo: "Fácil",
    riego: "Bajo",
    sol: "Pleno sol",
    datos_curiosos: "Sus segmentos se desprenden fácilmente y pueden enraizar para formar nuevas plantas.",
    emoji: "🌵",
    color: "bg-lime-500",
  },
  {
    id: 11,
    nombre_comun: "Ciruelo Cimarrón",
    nombre_cientifico: "Cyrtocarpa edulis",
    familia: "Anacardiaceae",
    descripcion:
      "Árbol 5 – 10 m; hojas compuestas; flores blancas-amarillas; drupas amarillo-anaranjadas con pulpa agridulce.",
    usos: "Medicinal; alimenticio; ornamental.",
    imagen: "/placeholder.svg?height=300&width=400",
    categoria: "Comestibles",
    dificultad_cultivo: "Moderada",
    riego: "Moderado",
    sol: "Pleno sol",
    datos_curiosos: "Sus frutos tienen un sabor agridulce muy apreciado y son ricos en vitaminas.",
    emoji: "🍑",
    color: "bg-orange-500",
  },
  {
    id: 12,
    nombre_comun: "Cordoncillo",
    nombre_cientifico: "Elytraria imbricata",
    familia: "Acanthaceae",
    descripcion: "Hierba rasante (< 30 cm), hojas en roseta, flores blancas-azul pálido; muy resistente a sequía.",
    usos: "Medicinal; ornamental.",
    imagen: "/placeholder.svg?height=300&width=400",
    categoria: "Medicinales",
    dificultad_cultivo: "Fácil",
    riego: "Bajo",
    sol: "Sol parcial",
    datos_curiosos: "También conocido como Cordón de San Juan, es una planta muy resistente que crece pegada al suelo.",
    emoji: "🌱",
    color: "bg-blue-400",
  },
  {
    id: 13,
    nombre_comun: "Golondrina",
    nombre_cientifico: "Euphorbia polycarpa",
    familia: "Euphorbiaceae",
    descripcion:
      "Hierba rastrera-erecta (< 30 cm), tallos finos; flores diminutas blanco-amarillentas; se adapta a suelos pedregosos.",
    usos: "Medicinal; ornamental.",
    imagen: "/placeholder.svg?height=300&width=400",
    categoria: "Medicinales",
    dificultad_cultivo: "Fácil",
    riego: "Bajo",
    sol: "Pleno sol",
    datos_curiosos: "Su nombre se debe a que sus pequeñas flores parecen volar como golondrinas cuando hay viento.",
    emoji: "🕊️",
    color: "bg-yellow-400",
  },
  {
    id: 14,
    nombre_comun: "Guatamote",
    nombre_cientifico: "Baccharis salicifolia",
    familia: "Asteraceae",
    descripcion:
      "Arbusto hasta 3 m, hojas estrechas; cabezuelas blancas-amarillas casi todo el año; frecuente cerca de agua.",
    usos: "Medicinal; combustible; maderable.",
    conservacion: "Preocupación menor",
    imagen: "/placeholder.svg?height=300&width=400",
    categoria: "Medicinales",
    dificultad_cultivo: "Fácil",
    riego: "Moderado",
    sol: "Sol parcial",
    datos_curiosos: "Florece casi todo el año y es común encontrarlo cerca de fuentes de agua.",
    emoji: "🌾",
    color: "bg-green-300",
  },
  {
    id: 15,
    nombre_comun: "Incienso",
    nombre_cientifico: "Encelia farinosa",
    familia: "Asteraceae",
    descripcion:
      "Arbusto 0.5 – 1.5 m; hojas gris-polvosas; flores amarillas primaverales; muy tolerante a sequía y suelos pobres.",
    usos: "Medicinal; resina; ornamental.",
    imagen: "/placeholder.svg?height=300&width=400",
    categoria: "Medicinales",
    dificultad_cultivo: "Fácil",
    riego: "Bajo",
    sol: "Pleno sol",
    datos_curiosos: "Sus hojas tienen una textura polvosa que las protege del sol intenso del desierto.",
    emoji: "🌻",
    color: "bg-yellow-600",
  },
  {
    id: 16,
    nombre_comun: "Istafiate",
    nombre_cientifico: "Ambrosia confertiflora",
    familia: "Asteraceae",
    descripcion:
      "Hierba perenne 0.5 – 1.5 m, hojas lanceoladas grisáceas; flores diminutas amarillas en espigas densas.",
    usos: "Medicinal; repelente.",
    imagen: "/placeholder.svg?height=300&width=400",
    categoria: "Medicinales",
    dificultad_cultivo: "Fácil",
    riego: "Bajo",
    sol: "Pleno sol",
    datos_curiosos: "También conocido como Estafiate, tradicionalmente se usa como repelente natural de insectos.",
    emoji: "🌿",
    color: "bg-gray-400",
  },
  {
    id: 17,
    nombre_comun: "Lomboy Blanco",
    nombre_cientifico: "Jatropha cinerea",
    familia: "Euphorbiaceae",
    descripcion:
      "Arbusto hasta 5 m, ramas retorcidas, hojas grandes grisáceas; exuda resina rojiza; flores amarillo-crema.",
    usos: "Medicinal.",
    conservacion: "Preocupación menor",
    imagen: "/placeholder.svg?height=300&width=400",
    categoria: "Medicinales",
    dificultad_cultivo: "Moderada",
    riego: "Bajo",
    sol: "Pleno sol",
    datos_curiosos: "Exuda una resina rojiza característica cuando se corta su corteza.",
    emoji: "🌳",
    color: "bg-gray-300",
  },
  {
    id: 18,
    nombre_comun: "Manzanilla Cimarrona",
    nombre_cientifico: "Pectis multiseta",
    familia: "Asteraceae",
    descripcion: "Hierba anual 10 – 30 cm, hojas lineares aromáticas (olor limón); cabezuelas amarillas verano-otoño.",
    usos: "Forrajero; medicinal; aromática; ornamental.",
    imagen: "/placeholder.svg?height=300&width=400",
    categoria: "Aromáticas",
    dificultad_cultivo: "Fácil",
    riego: "Bajo",
    sol: "Pleno sol",
    datos_curiosos: "Sus hojas desprenden un agradable aroma a limón cuando se frotan.",
    emoji: "🍋",
    color: "bg-yellow-300",
  },
  {
    id: 19,
    nombre_comun: "Mauto",
    nombre_cientifico: "Lysiloma divaricatum",
    familia: "Fabaceae",
    descripcion:
      "Árbol mediano, hojas bipinnadas; flores esféricas blancas-crema; vainas largas con semillas aplanadas.",
    usos: "Maderable; combustible; tinte natural; forrajero.",
    conservacion: "Preocupación menor",
    imagen: "/placeholder.svg?height=300&width=400",
    categoria: "Maderables",
    dificultad_cultivo: "Moderada",
    riego: "Moderado",
    sol: "Pleno sol",
    datos_curiosos: "Su madera es muy apreciada para construcción y sus flores atraen muchos polinizadores.",
    emoji: "🌳",
    color: "bg-brown-500",
  },
  {
    id: 20,
    nombre_comun: "Mesquite",
    nombre_cientifico: "Neltuma articulata",
    familia: "Fabaceae",
    descripcion:
      "Árbol espinoso hasta 10 m, tronco retorcido, madera densa marrón oscuro; flores amarillas; vainas con semillas comestibles.",
    usos: "Maderable; combustible; tinte; forrajero; medicinal.",
    conservacion: "Preocupación menor",
    imagen: "/placeholder.svg?height=300&width=400",
    categoria: "Maderables",
    dificultad_cultivo: "Fácil",
    riego: "Bajo",
    sol: "Pleno sol",
    datos_curiosos: "Sus raíces pueden extenderse hasta 50 metros para buscar agua subterránea.",
    emoji: "🌳",
    color: "bg-amber-700",
  },
  {
    id: 21,
    nombre_comun: "Palma Real",
    nombre_cientifico: "Washingtonia robusta",
    familia: "Arecaceae",
    descripcion: "Palmera esbelta hasta 30 m; hojas en abanico >1 m; inflorescencias largas; frutos negros carnosos.",
    usos: "Maderable; ornamental; artesanal.",
    conservacion: "Preocupación menor",
    imagen: "/placeholder.svg?height=300&width=400",
    categoria: "Ornamentales",
    dificultad_cultivo: "Moderada",
    riego: "Moderado",
    sol: "Pleno sol",
    datos_curiosos: "También conocida como Palma Colorada, puede vivir más de 100 años y alcanzar 30 metros de altura.",
    emoji: "🌴",
    color: "bg-green-700",
  },
  {
    id: 22,
    nombre_comun: "Palo Adán",
    nombre_cientifico: "Fouquieria diguetii",
    familia: "Fouquieriaceae",
    descripcion:
      "Suculenta arborescente hasta 7 m, tronco cilíndrico; flores tubulares amarillo-crema; hojas caedizas.",
    usos: "Ornamental.",
    conservacion: "Vulnerable",
    imagen: "/placeholder.svg?height=300&width=400",
    categoria: "Endémicas",
    dificultad_cultivo: "Difícil",
    riego: "Bajo",
    sol: "Pleno sol",
    datos_curiosos: "Su forma única de tronco cilíndrico lo hace inconfundible en el paisaje desértico.",
    emoji: "🌿",
    color: "bg-green-800",
  },
  {
    id: 23,
    nombre_comun: "Palo Blanco",
    nombre_cientifico: "Lysiloma candidum",
    familia: "Fabaceae",
    descripcion:
      "Árbol hasta 10 m, corteza clara rugosa; hojas compuestas verde claro; flores blanco-crema en racimos; vainas aplanadas.",
    usos: "Maderable; combustible; tinte natural; forrajero.",
    conservacion: "Preocupación menor",
    imagen: "/placeholder.svg?height=300&width=400",
    categoria: "Maderables",
    dificultad_cultivo: "Moderada",
    riego: "Moderado",
    sol: "Sol parcial",
    datos_curiosos: "Su corteza clara y rugosa le da el nombre, y es muy apreciado para construcción.",
    emoji: "🤍",
    color: "bg-gray-200",
  },
  {
    id: 24,
    nombre_comun: "Palo Brasil",
    nombre_cientifico: "Haematoxylon brasiletto",
    familia: "Fabaceae",
    descripcion:
      "Árbol-arbusto 5 – 15 m, tronco retorcido corteza oscura; madera rojo-púrpura muy densa; flores amarillas en racimos.",
    usos: "Maderable; medicinal; tinte natural.",
    conservacion: "Preocupación menor",
    imagen: "/placeholder.svg?height=300&width=400",
    categoria: "Maderables",
    dificultad_cultivo: "Moderada",
    riego: "Bajo",
    sol: "Pleno sol",
    datos_curiosos: "Su madera rojo-púrpura fue históricamente muy valiosa para producir tintes.",
    emoji: "🟤",
    color: "bg-red-800",
  },
  {
    id: 25,
    nombre_comun: "Palo de Arco",
    nombre_cientifico: "Tecoma stans",
    familia: "Bignoniaceae",
    descripcion:
      "Arbusto-árbol hasta 5 m; flores amarillas en trompeta muy vistosas; hojas compuestas verde brillante.",
    usos: "Medicinal; ornamental; artesanal.",
    conservacion: "Preocupación menor",
    imagen: "/placeholder.svg?height=300&width=400",
    categoria: "Ornamentales",
    dificultad_cultivo: "Fácil",
    riego: "Moderado",
    sol: "Pleno sol",
    datos_curiosos: "Sus flores amarillas en forma de trompeta son muy llamativas y florecen gran parte del año.",
    emoji: "🎺",
    color: "bg-yellow-500",
  },
  {
    id: 26,
    nombre_comun: "Palo Eva",
    nombre_cientifico: "Chloroleucon mangense var. leucospermum",
    familia: "Fabaceae",
    descripcion:
      "Árbol hasta 8 m, corteza oscura; hojas compuestas verde brillante; flores blanco-crema en racimos; vainas alargadas.",
    usos: "Forrajero; combustible; maderable; medicinal.",
    conservacion: "Preocupación menor",
    imagen: "/placeholder.svg?height=300&width=400",
    categoria: "Maderables",
    dificultad_cultivo: "Moderada",
    riego: "Moderado",
    sol: "Pleno sol",
    datos_curiosos: "Es un excelente árbol forrajero y sus flores atraen gran cantidad de abejas.",
    emoji: "🌳",
    color: "bg-green-600",
  },
  {
    id: 27,
    nombre_comun: "Palo Zorrillo",
    nombre_cientifico: "Senna atomaria",
    familia: "Fabaceae",
    descripcion: "Árbol pequeño, hojas compuestas; flores amarillas en racimos; florece en temporada de lluvias.",
    usos: "Medicinal; forrajero; ornamental.",
    conservacion: "Preocupación menor",
    imagen: "/placeholder.svg?height=300&width=400",
    categoria: "Medicinales",
    dificultad_cultivo: "Fácil",
    riego: "Moderado",
    sol: "Pleno sol",
    datos_curiosos: "Florece principalmente durante la temporada de lluvias con abundantes flores amarillas.",
    emoji: "🌼",
    color: "bg-yellow-400",
  },
  {
    id: 28,
    nombre_comun: "Papache",
    nombre_cientifico: "Randia capitata",
    familia: "Rubiaceae",
    descripcion: "Arbusto hasta 3 m, ramas espinosas; flores blancas fragantes; frutos amarillos-anaranjados.",
    usos: "Maderable; combustible; alimenticio.",
    conservacion: "Preocupación menor",
    imagen: "/placeholder.svg?height=300&width=400",
    categoria: "Comestibles",
    dificultad_cultivo: "Moderada",
    riego: "Moderado",
    sol: "Sol parcial",
    datos_curiosos: "Sus flores blancas son muy fragantes y sus frutos son comestibles.",
    emoji: "🍊",
    color: "bg-orange-400",
  },
  {
    id: 29,
    nombre_comun: "Pitaya Agria",
    nombre_cientifico: "Stenocereus gummosus",
    familia: "Cactaceae",
    descripcion: "Cactus columnar hasta 5 m; flores nocturnas blancas; frutos pera dulces-jugosos.",
    usos: "Combustible; medicinal; alimenticio.",
    conservacion: "Preocupación menor; CITES Apéndice II",
    imagen: "/placeholder.svg?height=300&width=400",
    categoria: "Cactáceas",
    dificultad_cultivo: "Moderada",
    riego: "Bajo",
    sol: "Pleno sol",
    datos_curiosos: "Sus frutos tienen forma de pera y son muy jugosos, con un sabor ligeramente ácido.",
    emoji: "🍐",
    color: "bg-pink-400",
  },
  {
    id: 30,
    nombre_comun: "Pitaya Dulce",
    nombre_cientifico: "Stenocereus thurberi",
    familia: "Cactaceae",
    descripcion: "Cactus columnar hasta 6 m; flores blancas nocturnas; frutos carnosos muy dulces.",
    usos: "Ornamental; medicinal; alimenticio.",
    conservacion: "Preocupación menor; CITES Apéndice II",
    imagen: "/placeholder.svg?height=300&width=400",
    categoria: "Cactáceas",
    dificultad_cultivo: "Moderada",
    riego: "Bajo",
    sol: "Pleno sol",
    datos_curiosos:
      "Sus frutos son extremadamente dulces y fueron una fuente importante de alimento para los pueblos originarios.",
    emoji: "🍓",
    color: "bg-red-400",
  },
  {
    id: 31,
    nombre_comun: "Romerillón",
    nombre_cientifico: "Ambrosia monogyra",
    familia: "Asteraceae",
    descripcion: "Arbusto hasta 2 m, hojas divididas grisáceas; flores pequeñas amarillas; muy tolerante a sequía.",
    usos: "Forrajero; ornamental.",
    imagen: "/placeholder.svg?height=300&width=400",
    categoria: "Forrajeras",
    dificultad_cultivo: "Fácil",
    riego: "Bajo",
    sol: "Pleno sol",
    datos_curiosos: "Es extremadamente tolerante a la sequía y puede sobrevivir largos períodos sin agua.",
    emoji: "🌾",
    color: "bg-gray-500",
  },
  {
    id: 32,
    nombre_comun: "Salvia",
    nombre_cientifico: "Condea tephrodes",
    familia: "Lamiaceae",
    descripcion: "Arbusto hasta 1.5 m; hojas opuestas verdes; flores blancas en inflorescencias; atrae polinizadores.",
    usos: "Ornamental; medicinal; forrajero.",
    imagen: "/placeholder.svg?height=300&width=400",
    categoria: "Aromáticas",
    dificultad_cultivo: "Fácil",
    riego: "Moderado",
    sol: "Sol parcial",
    datos_curiosos: "Sus flores blancas atraen gran cantidad de mariposas y otros polinizadores.",
    emoji: "🦋",
    color: "bg-white",
  },
  {
    id: 33,
    nombre_comun: "San Miguelito",
    nombre_cientifico: "Antigonon leptopus",
    familia: "Polygonaceae",
    descripcion:
      "Trepadora hasta 10 m; tallos flexibles; flores campanuladas rosa/rojas/blancas en racimos; muy atractiva a polinizadores.",
    usos: "Medicinal; ornamental.",
    imagen: "/placeholder.svg?height=300&width=400",
    categoria: "Trepadoras",
    dificultad_cultivo: "Fácil",
    riego: "Moderado",
    sol: "Pleno sol",
    datos_curiosos: "Es una trepadora muy vigorosa que puede cubrir grandes extensiones con sus flores coloridas.",
    emoji: "🌺",
    color: "bg-pink-600",
  },
  {
    id: 34,
    nombre_comun: "Talayote",
    nombre_cientifico: "Matelea fruticosa",
    familia: "Apocynaceae",
    descripcion:
      "Trepadora hasta 5 m; hojas opuestas; flores amarillo-naranja aromáticas; prefiere suelos bien drenados.",
    usos: "Ornamental; medicinal; alimenticio.",
    imagen: "/placeholder.svg?height=300&width=400",
    categoria: "Trepadoras",
    dificultad_cultivo: "Moderada",
    riego: "Moderado",
    sol: "Sol parcial",
    datos_curiosos: "Sus flores amarillo-naranja son muy aromáticas y atraen polinizadores especializados.",
    emoji: "🧡",
    color: "bg-orange-500",
  },
  {
    id: 35,
    nombre_comun: "Toloache",
    nombre_cientifico: "Datura discolor",
    familia: "Solanaceae",
    descripcion:
      "Hierba perenne hasta 1.5 m; hojas grandes; flores trompeta blancas-púrpura perfumadas; cápsulas espinosas.",
    usos: "Rituales; alucinógeno; medicinal.",
    imagen: "/placeholder.svg?height=300&width=400",
    categoria: "Rituales",
    dificultad_cultivo: "Difícil",
    riego: "Moderado",
    sol: "Sol parcial",
    datos_curiosos: "Planta sagrada para muchas culturas indígenas, pero extremadamente tóxica y peligrosa.",
    emoji: "⚠️",
    color: "bg-purple-600",
  },
  {
    id: 36,
    nombre_comun: "Torote Colorado",
    nombre_cientifico: "Bursera microphylla",
    familia: "Burseraceae",
    descripcion: "Árbol hasta 5 m; corteza que se desprende; hojas pequeñas; flores aromáticas; drupas con semillas.",
    usos: "Medicinal; combustible; tinte natural; ornamental.",
    conservacion: "Preocupación menor",
    imagen: "/placeholder.svg?height=300&width=400",
    categoria: "Endémicas",
    dificultad_cultivo: "Moderada",
    riego: "Bajo",
    sol: "Pleno sol",
    datos_curiosos: "Su corteza se desprende en láminas rojizas, dándole su nombre característico.",
    emoji: "🟤",
    color: "bg-red-700",
  },
  {
    id: 37,
    nombre_comun: "Viejitos",
    nombre_cientifico: "Mammillaria armillata",
    familia: "Cactaceae",
    descripcion:
      "Cactus globoso-cilíndrico hasta 30 cm; tubérculos prominentes; espinas blancas; flores pequeñas rosa-blancas.",
    usos: "Ornamental; alimenticio.",
    conservacion: "Vulnerable; CITES Apéndice II",
    imagen: "/placeholder.svg?height=300&width=400",
    categoria: "Cactáceas",
    dificultad_cultivo: "Moderada",
    riego: "Bajo",
    sol: "Pleno sol",
    datos_curiosos: "Su nombre se debe a que sus espinas blancas le dan apariencia de cabello canoso.",
    emoji: "👴",
    color: "bg-gray-300",
  },
  {
    id: 38,
    nombre_comun: "Vinorama",
    nombre_cientifico: "Vachellia farnesiana",
    familia: "Fabaceae",
    descripcion: "Arbusto-árbol 6 m; corteza espinosa; flores amarillas aromáticas; vainas con semillas.",
    usos: "Forraje; medicinal; tinte natural.",
    conservacion: "Preocupación menor",
    imagen: "/placeholder.svg?height=300&width=400",
    categoria: "Forrajeras",
    dificultad_cultivo: "Fácil",
    riego: "Bajo",
    sol: "Pleno sol",
    datos_curiosos: "Sus flores amarillas son extremadamente aromáticas y se usan en perfumería.",
    emoji: "🌼",
    color: "bg-yellow-600",
  },
  {
    id: 39,
    nombre_comun: "Zalate",
    nombre_cientifico: "Ficus petiolaris",
    familia: "Moraceae",
    descripcion:
      "Árbol hasta 10 m; raíces superficiales sobre rocas; hojas grandes acorazonadas; siconos que dan pequeños frutos.",
    usos: "Ornamental; medicinal; alimenticio; forrajero.",
    conservacion: "Preocupación menor",
    imagen: "/placeholder.svg?height=300&width=400",
    categoria: "Ornamentales",
    dificultad_cultivo: "Moderada",
    riego: "Moderado",
    sol: "Sol parcial",
    datos_curiosos: "Sus raíces crecen sobre las rocas creando formas espectaculares y únicas.",
    emoji: "🌳",
    color: "bg-green-500",
  },
  {
    id: 40,
    nombre_comun: "Zantinia",
    nombre_cientifico: "Aloysia barbata",
    familia: "Verbenaceae",
    descripcion:
      "Arbusto 1.5 m, tallos delgados; hojas lanceoladas con ligera pubescencia; flores blancas-lilas aromáticas.",
    usos: "Medicinal; infusión.",
    imagen: "/placeholder.svg?height=300&width=400",
    categoria: "Aromáticas",
    dificultad_cultivo: "Fácil",
    riego: "Moderado",
    sol: "Sol parcial",
    datos_curiosos: "También conocida como Poleo, se usa tradicionalmente para hacer infusiones medicinales.",
    emoji: "🍵",
    color: "bg-purple-400",
  },
  {
    id: 41,
    nombre_comun: "Pino Salado",
    nombre_cientifico: "Tamarix aphylla",
    familia: "Tamaricaceae",
    descripcion:
      "Árbol/arbusto siempre verde hasta 10 m; flores verdosas-rosadas; cápsulas con semillas diminutas dispersadas por viento.",
    usos: "Ornamental; sombra; rompe-vientos.",
    imagen: "/placeholder.svg?height=300&width=400",
    categoria: "Ornamentales",
    dificultad_cultivo: "Fácil",
    riego: "Moderado",
    sol: "Pleno sol",
    datos_curiosos: "Es muy tolerante a la salinidad y se usa como cortina rompe-vientos en zonas costeras.",
    emoji: "🌲",
    color: "bg-green-700",
  },
]

export const categorias = [
  "Todas",
  "Cactáceas",
  "Leguminosas",
  "Medicinales",
  "Ornamentales",
  "Suculentas",
  "Endémicas",
  "Maderables",
  "Comestibles",
  "Aromáticas",
  "Forrajeras",
  "Trepadoras",
  "Rituales",
]

export const obtenerPlantaPorId = (id: number): Planta | undefined => {
  return plantasBCS.find((planta) => planta.id === id)
}

export const buscarPlantas = (termino: string): Planta[] => {
  const terminoLower = termino.toLowerCase()
  return plantasBCS.filter(
    (planta) =>
      planta.nombre_comun.toLowerCase().includes(terminoLower) ||
      planta.nombre_cientifico.toLowerCase().includes(terminoLower) ||
      planta.familia.toLowerCase().includes(terminoLower),
  )
}

export const obtenerPlantasPorCategoria = (categoria: string): Planta[] => {
  if (categoria === "Todas") return plantasBCS
  return plantasBCS.filter((planta) => planta.categoria === categoria)
}

export const obtenerCategorias = (): string[] => {
  return categorias
}
